spring:
  datasource:
    url: jdbc:mysql://rm-bp144v36b5041so3rwo.mysql.rds.aliyuncs.com:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true
    username: user_paco_test
    password: UserPacotest
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource